runtime: python310  # or python39

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F1

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
